### ISSUE TITLE
Essa variável sempre vale 0 e nunca é escrita

### ISSUE THREAD

**Issue by eduardomarossi** [brunoartc/EmbarcadosAPS2#10]
https://github.com/brunoartc/EmbarcadosAPS2/blob/54a416d69455df32a2599530fe09593672dd21fa/MXT_EXAMPLE_USART1/src/main.c#L545

Achei estranho,

**Comment by brunoartc** [comment]
Foi uma variável teste para salvar o estado da porta

**Comment by brunoartc** [comment]
9d2fef90928274d4ed540469d26ff9594dedd1e8
