### ISSUE TITLE
A tela fica toda vermelha se o botão não estiver apertado, é pra simular porta aberta? 

### ISSUE THREAD

**Issue by eduardomarossi** [brunoartc/EmbarcadosAPS2#14]
https://github.com/brunoartc/EmbarcadosAPS2/blob/54a416d69455df32a2599530fe09593672dd21fa/MXT_EXAMPLE_USART1/src/main.c#L559-L567

Pra facilitar o debug, alterei a condição pra porta estar aberta quando estiver apertado

**Comment by brunoartc** [comment]
Sim
