### ISSUE TITLE
Não funciona corretamente. O código enviado é o final?

### ISSUE THREAD

**Issue by eduardomarossi** [brunoartc/EmbarcadosAPS2#15]
Por favor verificar

Aqui na minha placa, o LCD fica todo bugado ao clicar na tela, nao exibe o tempo e vários textos ficam apagados, nao consigo trocar o ciclo ou acionar as funções.

**Comment by brunoartc** [comment]
No nosso funcionou corretamente nesta versão do código https://youtu.be/lwrHc1TUhFM
