### ISSUE TITLE
Precisa indicar autoria do código

### ISSUE THREAD

**Issue by eduardomarossi** [brunoartc/EmbarcadosAPS2#3]
https://github.com/brunoartc/EmbarcadosAPS2/blob/54a416d69455df32a2599530fe09593672dd21fa/MXT_EXAMPLE_USART1/src/main.c#L119-L129

Fonte:
[https://stackoverflow.com/questions/14564813/how-to-convert-integer-to-character-array-using-c/14564839#14564839](https://stackoverflow.com/questions/14564813/how-to-convert-integer-to-character-array-using-c/14564839#14564839)

**Comment by brunoartc** [comment]
Essa função não foi usada.

**Comment by brunoartc** [comment]
ceabcd8aca500287abae5b66b78d70b3c35d7547
