### ISSUE TITLE
Esses vetores poderiam ser constantes, já que o tamanho e os elementos não mudam.

### ISSUE THREAD

**Issue by eduardomarossi** [brunoartc/EmbarcadosAPS2#5]
https://github.com/brunoartc/EmbarcadosAPS2/blob/54a416d69455df32a2599530fe09593672dd21fa/MXT_EXAMPLE_USART1/src/main.c#L235-L261

Usar const

**Comment by brunoartc** [comment]
336c6d83adefec8b73036d54420bd10b5076ee91
