### ISSUE TITLE
Qual o objetivo desse if? Desligar/ligar o trecho de código?

### ISSUE THREAD

**Issue by eduardomarossi** [brunoartc/EmbarcadosAPS2#9]
https://github.com/brunoartc/EmbarcadosAPS2/blob/54a416d69455df32a2599530fe09593672dd21fa/MXT_EXAMPLE_USART1/src/main.c#L467

 Desligar/ligar o trecho de código foi o único uso que pensei (alternativa a bloco de comentários)

Poderia usar o #define e #ifdef também

**Comment by brunoartc** [comment]
sim
